---@class discord.Emoji
---@field id discord.Snowflake | nil
---@field name string
---@field roles discord.Role[]
---@field user discord.User
---@field require_colors boolean | nil
---@field managed boolean | nil
---@field animated boolean | nil
---@field available boolean | nil
