---@class discord.RoleTags
---@field bot_id discord.Snowflake
---@field integration_id discord.Snowflake
---@field premium_subscrible nil
---@field subscription_listing_id discord.Snowflake
---@field available_for_purchace nil
---@field guild_connections nil

---@class discord.Role
---@field id discord.Snowflake
---@field name string
---@field color integer
---@field hoist boolean
---@field icon string | nil
---@field unicode_emoji string | nil
---@field position integer
---@field permissions string
---@field managed boolean
---@field mentionable boolean
---@field tags discord.RoleTags
---@field flags integer
